modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC0-1.0"

[[mods]]
modId = "enchant_outline"
version = "3.2"
displayName = "Enchantment Glint Outline"
displayURL = "https://github.com/Da0neDatGotAway/enchant-outline"
logoFile = "../assets/enchant_outline/icon.png"
authors = "Da0neDatGotAway"
credits = "Contributors: yo314159at, Igrium"
description = 'Adds a fancy outline to enchanted items. Works with resource packs and vanilla shaders.'

[[mixins]]
config = "enchant_outline.mixins.json"

[[dependencies.enchant_outline]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchant_outline]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchant_outline]]
modId = "yacl"
type = "optional"
versionRange = "[3.0,)"
ordering = "NONE"
side = "BOTH"