modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC0-1.0"

[[mods]]
modId = "enchant_outline"
version = "${mod_version}"
displayName = "Enchantment Glint Outline"
displayURL = "https://github.com/stellarspmc/better-enchants"
logoFile = "assets/enchant_outline/icon.png"
authors = "tcfplayz"
credits = "Contributors: yo314159at, Igrium, Da0neDatGotAway"
description = 'Adds a fancy outline to enchanted items. Works with resource packs and vanilla shaders.'

[[mixins]]
config = "enchant_outline.mixins.json"

[[dependencies.enchant_outline]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.enchant_outline]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.enchant_outline]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange = "[3.8,)"
ordering = "NONE"
side = "CLIENT"