name: CI Build

run-name: Build (${{ github.ref_name }}) by @${{ github.actor }}

on:
  push:
    branches: [ "1.21.1" ]
  pull_request:
    branches: [ "1.21.1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload Built File
        uses: actions/upload-artifact@v4
        with:
          name: enchant-outline-1.21.1-${{ github.sha }}
          path: build/libs/*.jar
          if-no-files-found: error